/-
Copyright (c) 2026 raylei50653. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: raylei50653
-/
import Math.AttachmentBudget

/-! # Attachment geometry as a cut block necklace

Generate a word by rotating `0^a 1^b 2^c` and cutting it into five packets of prescribed
lengths. A packet must have no repeated triangle position; its elements, translated by
one global triangle orientation, are the attachments at that boundary vertex.

The normal form below contains no run, fan rotations, winding predicate, colouring, or
Hall witness. Its equivalence with `AnnulusAccept` is proved by reconstructing the fans.
It characterizes the existing geometry grammar, not arbitrary disk embeddings. -/

namespace FiveBoundary.GeometryDFA
open ColorDFA

/-- Cut a list into packets of the specified lengths, in order. -/
def cutPackets {α : Type*} : List ℕ → List α → List (List α)
  | [], _ => []
  | n :: ns, l => l.take n :: cutPackets ns (l.drop n)

theorem cutPackets_length {α : Type*} (ns : List ℕ) (l : List α) :
    (cutPackets ns l).length = ns.length := by
  induction ns generalizing l with
  | nil => rfl
  | cons n ns ih => simp [cutPackets, ih]

theorem cutPackets_flatten {α : Type*} (ns : List ℕ) (l : List α)
    (h : ns.sum = l.length) : (cutPackets ns l).flatten = l := by
  induction ns generalizing l with
  | nil => simp only [List.sum_nil] at h; simp [cutPackets, List.length_eq_zero_iff.mp h.symm]
  | cons n ns ih =>
    simp only [List.sum_cons] at h
    simp only [cutPackets, List.flatten_cons]
    rw [ih (l.drop n) (by simp only [List.length_drop]; omega), List.take_append_drop]

theorem cutPackets_of_lengths {α : Type*} (ls : List (List α)) :
    cutPackets (ls.map List.length) ls.flatten = ls := by
  induction ls with
  | nil => rfl
  | cons l ls ih => simp [cutPackets, ih]

/-- The three homogeneous blocks, with zero-length blocks allowed. -/
def necklace (a b c : ℕ) : List (Fin 3) :=
  List.replicate a 0 ++ List.replicate b 1 ++ List.replicate c 2

/-- Scalar parameters of a cut block necklace. `widths` lists the five boundary fan sizes. -/
structure NecklaceCuts where
  orientation : Bool
  a : ℕ
  b : ℕ
  c : ℕ
  offset : ℕ
  widths : List ℕ
  five : widths.length = 5
  total : widths.sum = a + b + c

namespace NecklaceCuts

def packets (s : NecklaceCuts) : List (List (Fin 3)) :=
  cutPackets s.widths ((necklace s.a s.b s.c).rotate s.offset)

theorem packets_length (s : NecklaceCuts) : s.packets.length = 5 := by
  rw [packets, cutPackets_length, s.five]

def packet (s : NecklaceCuts) (i : Fin 5) : List (Fin 3) := s.packets[i.val]'(by
  rw [s.packets_length]; exact i.isLt)

/-- Each packet is a set of triangle positions, so a repeated position is forbidden. -/
def Valid (s : NecklaceCuts) : Prop := ∀ i, (s.packet i).Nodup

/-- Translate normalized triangle positions back to the actual interior labels. -/
def word (s : NecklaceCuts) : Word := fun i => ((s.packet i).map (pos s.orientation)).toFinset

theorem packets_flatten (s : NecklaceCuts) :
    s.packets.flatten = (necklace s.a s.b s.c).rotate s.offset := by
  apply cutPackets_flatten
  simpa [necklace, Nat.add_assoc] using s.total

theorem packets_eq_ofFn (s : NecklaceCuts) : s.packets = List.ofFn s.packet := by
  apply List.ext_getElem
  · simp [s.packets_length]
  · intro i h1 h2
    rw [List.getElem_ofFn]
    rfl

end NecklaceCuts

/-- A word has attachment normal form if it is generated by a valid cut block necklace. -/
def AttachmentNormalForm (w : Word) : Prop :=
  ∃ s : NecklaceCuts, s.Valid ∧ s.word = w

/-! ### Local reconstruction: a duplicate-free packet with at most one turn is a fan -/

/-- Only a single packet is checked here (length at most three), not attachment words. -/
theorem packet_realizes_fan (o : Bool) (l : List (Fin 3)) (hn : l.Nodup)
    (hs : stepSum l ≤ 3) :
    ∃ r : Fin 3, (fan o (l.map (pos o)).toFinset r).map (pos o) = l := by
  have hl : l.length ≤ 3 := by
    simpa using hn.length_le_card
  cases l with
  | nil => revert o; decide +kernel
  | cons a l =>
    cases l with
    | nil => revert o a; decide +kernel
    | cons b l =>
      cases l with
      | nil => revert o a b; decide +kernel
      | cons c l =>
        have he : l = [] := by
          simp only [List.length_cons] at hl
          simpa using (show l.length = 0 by omega)
        subst l
        revert o a b c; decide +kernel

/-! ### Equivalence with the geometry grammar -/

theorem normalForm_of_runOK (w : Word) (ρ : Run) (h : RunOK w ρ) :
    AttachmentNormalForm w := by
  let F := fun i => (fan ρ.1 (w i) (ρ.2 i)).map (pos ρ.1)
  let ls := List.ofFn F
  have he : ls.flatten = (sequence w ρ).map (fun e => pos ρ.1 e.2) := by
    dsimp only [ls]
    rw [List.ofFn_eq_map, ← List.flatMap_def]
    simp only [sequence, List.map_flatMap, List.map_map, Function.comp_def]
    rfl
  obtain ⟨n, a, b, c, hblocks⟩ := (runOK_iff_blocks w ρ).mp h
  rw [← he] at hblocks
  change ls.flatten.rotate n = necklace a b c at hblocks
  have hinv := List.rotate_eq_iff.mp hblocks
  let s : NecklaceCuts := {
    orientation := ρ.1, a := a, b := b, c := c
    offset := (necklace a b c).length - n % (necklace a b c).length
    widths := ls.map List.length
    five := by simp [ls]
    total := by
      have hh := congrArg List.length hblocks
      simpa [List.length_flatten, necklace, Nat.add_assoc] using hh }
  have hp : s.packets = ls := by
    change cutPackets (ls.map List.length) _ = ls
    rw [← hinv]
    exact cutPackets_of_lengths ls
  have hpi : ∀ i, s.packet i = F i := by
    intro i
    simp only [NecklaceCuts.packet, hp, ls, List.getElem_ofFn]
  refine ⟨s, ?_, ?_⟩
  · intro i
    rw [hpi]
    exact List.Nodup.map (fun _ _ hh => pos_injective ρ.1 hh) (fan_nodup _ _ _)
  · funext i
    simp only [NecklaceCuts.word, hpi]
    change (((fan ρ.1 (w i) (ρ.2 i)).map (pos ρ.1)).map (pos ρ.1)).toFinset = w i
    ext k
    simp [List.map_map, Function.comp_def, pos_involutive, mem_fan]

theorem NecklaceCuts.stepSum_le_three (s : NecklaceCuts) : stepSum s.packets.flatten ≤ 3 := by
  rw [s.packets_flatten, stepSum_rotate]
  rcases stepSum_blocks s.a s.b s.c with h | h <;>
    change stepSum (necklace s.a s.b s.c) = _ at h <;> omega

/-- Every valid cut necklace admits fan rotations realizing exactly its packets. -/
theorem NecklaceCuts.accept (s : NecklaceCuts) (h : s.Valid) : AnnulusAccept s.word := by
  have hs : ∀ i, stepSum (s.packet i) ≤ 3 := by
    intro i
    apply (stepSum_le_of_sublist (List.sublist_flatten_of_mem ?_)).trans s.stepSum_le_three
    rw [s.packets_eq_ofFn]
    exact List.mem_ofFn.mpr ⟨i, rfl⟩
  choose r hr using fun i => packet_realizes_fan s.orientation (s.packet i) (h i) (hs i)
  refine ⟨(s.orientation, r), ?_⟩
  have he : (sequence s.word (s.orientation, r)).map (fun e => pos s.orientation e.2) =
      s.packets.flatten := by
    rw [s.packets_eq_ofFn]
    simp only [sequence, List.map_flatMap, List.map_map, Function.comp_def,
      List.ofFn_eq_map, ← List.flatMap_def]
    congr 1
    funext i
    exact hr i
  change winding s.word (s.orientation, r) = 0 ∨ winding s.word (s.orientation, r) = 3
  rw [winding_eq_stepSum, he, s.packets_flatten, stepSum_rotate]
  exact stepSum_blocks s.a s.b s.c

/-- **Attachment geometry normal form.** Accepting words are exactly the words obtained
by cutting a cyclic three-block necklace into five duplicate-free packets. -/
theorem annulusAccept_iff_normalForm (w : Word) :
    AnnulusAccept w ↔ AttachmentNormalForm w := by
  constructor
  · rintro ⟨ρ, h⟩
    exact normalForm_of_runOK w ρ h
  · rintro ⟨s, h, rfl⟩
    exact s.accept h

/-! ### The parameters are geometric: block sizes equal attachment degrees -/

theorem NecklaceCuts.mem_word_iff (s : NecklaceCuts) (i : Fin 5) (k : Fin 3) :
    pos s.orientation k ∈ s.word i ↔ k ∈ s.packet i := by
  simp only [word, List.mem_toFinset, List.mem_map]
  constructor
  · rintro ⟨j, hj, he⟩
    exact pos_injective s.orientation he ▸ hj
  · intro hk
    exact ⟨k, hk, rfl⟩

theorem NecklaceCuts.degree_eq_count (s : NecklaceCuts) (h : s.Valid) (k : Fin 3) :
    (linksOf s.word (pos s.orientation k)).card = s.packets.flatten.count k := by
  rw [s.packets_eq_ofFn, List.ofFn_eq_map, ← List.flatMap_def, List.count_flatMap]
  simp only [Function.comp_def]
  rw [← List.ofFn_eq_map, List.sum_ofFn]
  simp only [linksOf, Finset.card_filter, s.mem_word_iff]
  apply Finset.sum_congr rfl
  intro i _
  exact (h i).count.symm

/-- The three block lengths are exactly the three attachment degrees in the chosen orientation. -/
theorem NecklaceCuts.degrees (s : NecklaceCuts) (h : s.Valid) :
    (linksOf s.word (pos s.orientation 0)).card = s.a ∧
    (linksOf s.word (pos s.orientation 1)).card = s.b ∧
    (linksOf s.word (pos s.orientation 2)).card = s.c := by
  have hc : ∀ k, (linksOf s.word (pos s.orientation k)).card = (necklace s.a s.b s.c).count k := by
    intro k
    rw [s.degree_eq_count h, s.packets_flatten]
    exact (List.rotate_perm _ _).count_eq k
  simp [hc, necklace, List.count_replicate]

theorem cutPackets_lengths {α : Type*} (ns : List ℕ) (l : List α)
    (h : ns.sum = l.length) : (cutPackets ns l).map List.length = ns := by
  induction ns generalizing l with
  | nil => rfl
  | cons n ns ih =>
    simp only [List.sum_cons] at h
    have hn : n ≤ l.length := by omega
    simp only [cutPackets, List.map_cons, List.length_take, Nat.min_eq_left hn]
    rw [ih (l.drop n) (by simp only [List.length_drop]; omega)]

/-- The prescribed cuts are the actual sizes of the boundary fans. -/
theorem NecklaceCuts.packet_lengths (s : NecklaceCuts) : s.packets.map List.length = s.widths := by
  apply cutPackets_lengths
  simpa [necklace, Nat.add_assoc] using s.total

/-- Invalid long packets cannot hide duplicate attachments through conversion to a set. -/
theorem NecklaceCuts.packet_length_eq_card (s : NecklaceCuts) (h : s.Valid) (i : Fin 5) :
    (s.packet i).length = (s.word i).card := by
  rw [word, List.toFinset_card_of_nodup
    (List.Nodup.map (fun _ _ hh => pos_injective s.orientation hh) (h i)), List.length_map]

/-- Every valid normal form obeys the structural eight-attachment bound. -/
theorem NecklaceCuts.total_le_eight (s : NecklaceCuts) (h : s.Valid) : s.a + s.b + s.c ≤ 8 := by
  obtain ⟨ρ, hρ⟩ := s.accept h
  have hb := runOK_attachmentCount_le_eight s.word ρ hρ
  have he : attachmentCount s.word = s.a + s.b + s.c := by
    have hc : attachmentCount s.word = s.widths.sum := by
      rw [← s.packet_lengths, s.packets_eq_ofFn]
      rw [List.ofFn_eq_map, List.map_map, ← List.ofFn_eq_map, List.sum_ofFn]
      simp only [Function.comp_def, s.packet_length_eq_card h, attachmentCount]
    exact hc.trans s.total
  omega

/-! ### Nondegenerate geometry: a packet cannot cross two block junctions -/

/-- Returning to the middle of three distinct positions requires a second turn. -/
theorem middle_return_stepSum (p q r : Fin 3) (hpq : p ≠ q) (hpr : p ≠ r) (hqr : q ≠ r) :
    stepSum [p, q, r, q] = 6 := by
  revert p q r; decide +kernel

/-- In a one-turn necklace, a contiguous three-distinct-position packet contains
all occurrences of its middle position. This lemma is independent of the boundary size. -/
theorem middle_count_eq_one (pre post : List (Fin 3)) (p q r : Fin 3)
    (hn : [p, q, r].Nodup) (hs : stepSum (pre ++ [p, q, r] ++ post) ≤ 3) :
    (pre ++ [p, q, r] ++ post).count q = 1 := by
  have hpq : p ≠ q := by simp only [List.nodup_cons, List.mem_cons] at hn; tauto
  have hpr : p ≠ r := by simp only [List.nodup_cons, List.mem_cons] at hn; tauto
  have hqr : q ≠ r := by simp only [List.nodup_cons, List.mem_cons] at hn; tauto
  have hrot : (pre ++ [p, q, r] ++ post).rotate pre.length = [p, q, r] ++ (post ++ pre) := by
    rw [List.append_assoc, List.rotate_append_length_eq, List.append_assoc]
  have hnot : q ∉ post ++ pre := by
    intro hm
    have hsub : [p, q, r, q].Sublist ([p, q, r] ++ (post ++ pre)) :=
      (List.Sublist.refl [p, q, r]).append (List.singleton_sublist.mpr hm)
    have hb := stepSum_le_of_sublist hsub
    rw [middle_return_stepSum p q r hpq hpr hqr, ← hrot, stepSum_rotate] at hb
    omega
  have hpre : q ∉ pre := fun hm => hnot (List.mem_append_right _ hm)
  have hpost : q ∉ post := fun hm => hnot (List.mem_append_left _ hm)
  simp [List.count_append, List.count_eq_zero.mpr hpre, List.count_eq_zero.mpr hpost,
    hpq, hqr.symm]

/-- A three-element packet forces a degree-one interior vertex.
Thus all-degree-at-least-two geometry has only empty, singleton and pair packets. -/
theorem NecklaceCuts.triple_packet_forces_degree_one (s : NecklaceCuts) (h : s.Valid)
    (i : Fin 5) (ht : (s.packet i).length = 3) :
    ∃ k : Fin 3, (linksOf s.word k).card = 1 := by
  obtain ⟨p, q, r, he⟩ : ∃ p q r, s.packet i = [p, q, r] := by
    generalize s.packet i = l at ht ⊢
    rcases l with _ | ⟨p, l⟩ <;> simp only [List.length_nil, List.length_cons] at ht
    · omega
    rcases l with _ | ⟨q, l⟩ <;> simp only [List.length_nil, List.length_cons] at ht
    · omega
    rcases l with _ | ⟨r, l⟩ <;> simp only [List.length_nil, List.length_cons] at ht
    · omega
    have : l = [] := List.length_eq_zero_iff.mp (by omega)
    exact ⟨p, q, r, by rw [this]⟩
  have hm : s.packet i ∈ s.packets := by
    rw [s.packets_eq_ofFn]
    exact List.mem_ofFn.mpr ⟨i, rfl⟩
  obtain ⟨pre, post, hparts⟩ := List.append_of_mem hm
  have hflat : s.packets.flatten = pre.flatten ++ [p, q, r] ++ post.flatten := by
    rw [hparts, List.flatten_append, List.flatten_cons, he, List.append_assoc]
  refine ⟨pos s.orientation q, ?_⟩
  rw [s.degree_eq_count h, hflat]
  apply middle_count_eq_one _ _ p q r
  · rw [← he]; exact h i
  · rw [← hflat]; exact s.stepSum_le_three

/-- **Boundary packet normal form in the nondegenerate branch.** All nonempty packets
are singletons or pairs, never triples. No colouring assumptions occur. -/
theorem NecklaceCuts.packet_le_two (s : NecklaceCuts) (h : s.Valid)
    (hd : ∀ k, 2 ≤ (linksOf s.word k).card) (i : Fin 5) : (s.packet i).length ≤ 2 := by
  have hl : (s.packet i).length ≤ 3 := by simpa using (h i).length_le_card
  by_contra hc
  obtain ⟨k, hk⟩ := s.triple_packet_forces_degree_one h i (by omega)
  have := hd k
  omega

/-- Three distinct triangle positions can make at most one turn only in forward order. -/
theorem three_positions_forward (p q r : Fin 3) (hpq : p ≠ q) (hpr : p ≠ r) (hqr : q ≠ r)
    (hs : stepSum [p, q, r] ≤ 3) : q = p + 1 := by
  revert p q r; decide +kernel

/-- A contiguous pair in a necklace using all three positions follows triangle orientation. -/
theorem pair_forward_of_all_mem (pre post : List (Fin 3)) (p q : Fin 3) (hpq : p ≠ q)
    (hm : ∀ k, k ∈ pre ++ [p, q] ++ post) (hs : stepSum (pre ++ [p, q] ++ post) ≤ 3) :
    q = p + 1 := by
  have third : ∀ p q : Fin 3, ∃ r : Fin 3, r ≠ p ∧ r ≠ q := by decide +kernel
  obtain ⟨r, hrp, hrq⟩ := third p q
  have hr := hm r
  have hrest : r ∈ post ++ pre := by
    simp only [List.mem_append, List.mem_cons, List.not_mem_nil, or_false] at hr ⊢
    rcases hr with (hr | hr) | hr
    · exact Or.inr hr
    · rcases hr with hr | hr
      · exact False.elim (hrp hr)
      · exact False.elim (hrq hr)
    · exact Or.inl hr
  have hrot : (pre ++ [p, q] ++ post).rotate pre.length = [p, q] ++ (post ++ pre) := by
    rw [List.append_assoc, List.rotate_append_length_eq, List.append_assoc]
  have hsub : [p, q, r].Sublist ([p, q] ++ (post ++ pre)) :=
    (List.Sublist.refl [p, q]).append (List.singleton_sublist.mpr hrest)
  have hb := stepSum_le_of_sublist hsub
  rw [← hrot, stepSum_rotate] at hb
  exact three_positions_forward p q r hpq hrp.symm hrq.symm (hb.trans hs)

theorem NecklaceCuts.all_mem_of_degrees (s : NecklaceCuts) (h : s.Valid)
    (hd : ∀ k, 2 ≤ (linksOf s.word k).card) : ∀ k, k ∈ s.packets.flatten := by
  intro k
  by_contra hn
  have hz := List.count_eq_zero.mpr hn
  have hb := hd (pos s.orientation k)
  rw [s.degree_eq_count h, hz] at hb
  omega

/-- **Nondegenerate packet alphabet.** After choosing the one global triangle orientation,
each boundary vertex is empty, a singleton `p`, or the forward pair `[p,p + 1]`. -/
theorem NecklaceCuts.packet_shape (s : NecklaceCuts) (h : s.Valid)
    (hd : ∀ k, 2 ≤ (linksOf s.word k).card) (i : Fin 5) :
    s.packet i = [] ∨ (∃ p, s.packet i = [p]) ∨ (∃ p, s.packet i = [p, p + 1]) := by
  have hl := s.packet_le_two h hd i
  obtain he | ⟨p, he⟩ | ⟨p, q, he⟩ : s.packet i = [] ∨ (∃ p, s.packet i = [p]) ∨
      (∃ p q, s.packet i = [p, q]) := by
    generalize s.packet i = l at hl ⊢
    rcases l with _ | ⟨p, l⟩
    · exact Or.inl rfl
    rcases l with _ | ⟨q, l⟩
    · exact Or.inr (Or.inl ⟨p, rfl⟩)
    have : l = [] := List.length_eq_zero_iff.mp (by simp only [List.length_cons] at hl; omega)
    exact Or.inr (Or.inr ⟨p, q, by rw [this]⟩)
  · exact Or.inl he
  · exact Or.inr (Or.inl ⟨p, he⟩)
  · have hm : s.packet i ∈ s.packets := by
      rw [s.packets_eq_ofFn]
      exact List.mem_ofFn.mpr ⟨i, rfl⟩
    obtain ⟨pre, post, hparts⟩ := List.append_of_mem hm
    have hflat : s.packets.flatten = pre.flatten ++ [p, q] ++ post.flatten := by
      rw [hparts, List.flatten_append, List.flatten_cons, he, List.append_assoc]
    have hpq : p ≠ q := by have := h i; simpa [he] using this
    have hq := pair_forward_of_all_mem pre.flatten post.flatten p q hpq
      (by rw [← hflat]; exact s.all_mem_of_degrees h hd)
      (by rw [← hflat]; exact s.stepSum_le_three)
    exact Or.inr (Or.inr ⟨p, by rw [he, hq]⟩)

/-- Each of the three block junctions can be shared by at most one boundary packet.
This needs no minimum-degree hypothesis: it applies to any forward-pair packet. -/
theorem NecklaceCuts.forward_pair_count_le_one (s : NecklaceCuts) (p : Fin 3) :
    s.packets.count [p, p + 1] ≤ 1 := by
  by_contra hc
  have hsub : (List.replicate 2 [p, p + 1]).Sublist s.packets :=
    List.replicate_sublist_iff.mpr (by omega)
  have hb := stepSum_le_of_sublist hsub.flatten
  change stepSum [p, p + 1, p, p + 1] ≤ stepSum s.packets.flatten at hb
  have hn : ∀ p : Fin 3, p + 1 ≠ p := by decide +kernel
  rw [stepSum_alternating p (p + 1) (p + 1) (hn p) (hn p)] at hb
  have := s.stepSum_le_three
  omega

/-- The nondegenerate normal form has three singleton blocks and at most one shared
packet at each of the three forward junctions. Empty boundary packets are retained. -/
theorem annulusAccept_iff_nondegenerate_normalForm (w : Word)
    (hd : ∀ k, 2 ≤ (linksOf w k).card) :
    AnnulusAccept w ↔ ∃ s : NecklaceCuts, s.Valid ∧ s.word = w ∧
      (2 ≤ s.a ∧ 2 ≤ s.b ∧ 2 ≤ s.c) ∧
      (∀ i, s.packet i = [] ∨ (∃ p, s.packet i = [p]) ∨
        (∃ p, s.packet i = [p, p + 1])) ∧
      (∀ p, s.packets.count [p, p + 1] ≤ 1) := by
  constructor
  · intro ha
    obtain ⟨s, hs, he⟩ := (annulusAccept_iff_normalForm w).mp ha
    have hd' : ∀ k, 2 ≤ (linksOf s.word k).card := by rw [he]; exact hd
    obtain ⟨h0, h1, h2⟩ := s.degrees hs
    refine ⟨s, hs, he, ?_, s.packet_shape hs hd', s.forward_pair_count_le_one⟩
    exact ⟨h0 ▸ hd' _, h1 ▸ hd' _, h2 ▸ hd' _⟩
  · rintro ⟨s, hs, rfl, _⟩
    exact s.accept hs

/-! ### Incidence arithmetic of singleton blocks and shared junctions -/

/-- A packet contributes to exactly its singleton position or to its two junction endpoints. -/
theorem packet_count_decomposition (l : List (Fin 3))
    (h : l = [] ∨ (∃ p, l = [p]) ∨ (∃ p, l = [p, p + 1])) (k : Fin 3) :
    l.count k = (if l = [k] then 1 else 0) +
      (if l = [k, k + 1] then 1 else 0) + (if l = [k + 2, k] then 1 else 0) := by
  rcases h with rfl | ⟨p, rfl⟩ | ⟨p, rfl⟩
  · simp
  · revert p k; decide +kernel
  · revert p k; decide +kernel

theorem packet_counts (ls : List (List (Fin 3)))
    (h : ∀ l ∈ ls, l = [] ∨ (∃ p, l = [p]) ∨ (∃ p, l = [p, p + 1])) (k : Fin 3) :
    ls.flatten.count k = ls.count [k] + ls.count [k, k + 1] + ls.count [k + 2, k] := by
  induction ls with
  | nil => simp
  | cons l ls ih =>
    have hc := packet_count_decomposition l (h l (by simp)) k
    have hi := ih (fun l hl => h l (List.mem_cons_of_mem _ hl))
    simp only [List.flatten_cons, List.count_append, List.count_cons, beq_iff_eq] at *
    omega

/-- **Incidence normal form.** An interior degree is the number of its singleton packets
plus the two adjacent shared-junction indicators (each at most one). -/
theorem NecklaceCuts.degree_eq_singletons_add_junctions (s : NecklaceCuts) (h : s.Valid)
    (hd : ∀ k, 2 ≤ (linksOf s.word k).card) (k : Fin 3) :
    (linksOf s.word (pos s.orientation k)).card =
      s.packets.count [k] + s.packets.count [k, k + 1] + s.packets.count [k + 2, k] := by
  rw [s.degree_eq_count h]
  apply packet_counts
  intro l hl
  rw [s.packets_eq_ofFn, List.mem_ofFn] at hl
  obtain ⟨i, rfl⟩ := hl
  exact s.packet_shape h hd i

/-- In the nondegenerate alphabet, a pair of positions has exactly one possible packet order. -/
theorem packet_pair_membership (l : List (Fin 3))
    (h : l = [] ∨ (∃ p, l = [p]) ∨ (∃ p, l = [p, p + 1])) (p : Fin 3) :
    (p ∈ l ∧ p + 1 ∈ l) ↔ l = [p, p + 1] := by
  rcases h with rfl | ⟨q, rfl⟩ | ⟨q, rfl⟩
  · simp
  · revert p q; decide +kernel
  · revert p q; decide +kernel

theorem list_count_eq_sum_indicator {α : Type*} [BEq α] [LawfulBEq α] [DecidableEq α]
    (ls : List α) (x : α) :
    ls.count x = (ls.map (fun y => if y = x then 1 else 0)).sum := by
  induction ls with
  | nil => rfl
  | cons y ls ih => simp only [List.count_cons, beq_iff_eq, List.map_cons, List.sum_cons, ih]; omega

theorem NecklaceCuts.count_packet_eq_card (s : NecklaceCuts) (l : List (Fin 3)) :
    s.packets.count l = (Finset.univ.filter (fun i => s.packet i = l)).card := by
  rw [list_count_eq_sum_indicator, s.packets_eq_ofFn, List.ofFn_eq_map, List.map_map,
    ← List.ofFn_eq_map, List.sum_ofFn, Finset.card_filter]
  rfl

/-- Shared neighbours are exactly the packet at the corresponding block junction. -/
theorem NecklaceCuts.common_next_eq_junction (s : NecklaceCuts) (h : s.Valid)
    (hd : ∀ k, 2 ≤ (linksOf s.word k).card) (p : Fin 3) :
    linksOf s.word (pos s.orientation p) ∩ linksOf s.word (pos s.orientation (p + 1)) =
      Finset.univ.filter (fun i => s.packet i = [p, p + 1]) := by
  ext i
  simp only [Finset.mem_inter, linksOf, Finset.mem_filter, Finset.mem_univ, true_and,
    s.mem_word_iff]
  exact packet_pair_membership _ (s.packet_shape h hd i) p

/-- **Geometric corollary of normal form.** In the all-degree-at-least-two branch,
shared boundary neighbours of each pair number at most one. -/
theorem NecklaceCuts.common_next_le_one (s : NecklaceCuts) (h : s.Valid)
    (hd : ∀ k, 2 ≤ (linksOf s.word k).card) (p : Fin 3) :
    (linksOf s.word (pos s.orientation p) ∩
      linksOf s.word (pos s.orientation (p + 1))).card ≤ 1 := by
  rw [s.common_next_eq_junction h hd, ← s.count_packet_eq_card]
  exact s.forward_pair_count_le_one p

theorem runOK_common_le_one_of_degrees (w : Word) (ρ : Run) (h : RunOK w ρ)
    (hd : ∀ k, 2 ≤ (linksOf w k).card) (p q : Fin 3) (hpq : p ≠ q) :
    (linksOf w p ∩ linksOf w q).card ≤ 1 := by
  obtain ⟨s, hs, rfl⟩ := normalForm_of_runOK w ρ h
  have hn : pos s.orientation p ≠ pos s.orientation q := fun he => hpq (pos_injective _ he)
  have order : ∀ a b : Fin 3, a ≠ b → b = a+1 ∨ a = b+1 := by decide +kernel
  rcases order _ _ hn with he | he
  · have hc := s.common_next_le_one hs hd (pos s.orientation p)
    rw [← he, pos_involutive, pos_involutive] at hc
    exact hc
  · have hc := s.common_next_le_one hs hd (pos s.orientation q)
    rw [← he, pos_involutive, pos_involutive, Finset.inter_comm] at hc
    exact hc

theorem runOK_fan_card_le_two_of_degrees (w : Word) (ρ : Run) (h : RunOK w ρ)
    (hd : ∀ k, 2 ≤ (linksOf w k).card) (i : Fin 5) : (w i).card ≤ 2 := by
  obtain ⟨s, hs, rfl⟩ := normalForm_of_runOK w ρ h
  rw [← s.packet_length_eq_card hs]
  exact s.packet_le_two hs hd i

end FiveBoundary.GeometryDFA
