"""D2 views generated from the graph. D2 output is an artifact, never a source.

Edges point the way they are declared (A requires B draws A -> B) and views
use `direction: up`, so prerequisites appear above the documents using them.
"""
from __future__ import annotations

from .graph import Graph
from .model import relation_type

STYLES = {
    "requires": "",
    "derives_from": "style.stroke-dash: 4",
    "related": "style.stroke-dash: 2; style.stroke: \"#888888\"",
}


def q(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ") + '"'


def _node(graph: Graph, node_id: str, indent: str = "", root: str | None = None) -> str:
    node = graph.nodes[node_id]
    attrs = [f"tooltip: {q(node.title + ' — ' + node.path if node.title else node.path)}"]
    if node_id == root:
        attrs.append("style.stroke-width: 4")
        attrs.append('style.fill: "#fff3c4"')
    return f"{indent}{q(node_id)}: {{ {'; '.join(attrs)} }}"


def _edges(graph: Graph, ids: set[str], types) -> list[str]:
    lines, seen = [], set()
    for edge in graph.edges:
        if edge.type not in types or edge.source not in ids or edge.target not in ids:
            continue
        if relation_type(edge.type).symmetric:
            pair = (edge.type, frozenset((edge.source, edge.target)))
            if pair in seen:
                continue
            seen.add(pair)
            arrow = "--"
        else:
            arrow = "->"
        style = STYLES.get(edge.type, "style.stroke-dash: 6")
        body = f"label: {edge.type}" + (f"; {style}" if style else "")
        lines.append(f"{q(edge.source)} {arrow} {q(edge.target)}: {{ {body} }}")
    return lines


def _header(title: str, direction: str) -> list[str]:
    return [f"# Generated by docgraph — do not edit. {title}",
            f"direction: {direction}", ""]


def relation_view(graph: Graph, ids: set[str] | None = None, root: str | None = None) -> str:
    ids = set(graph.nodes) if ids is None else ids
    types = {e.type for e in graph.edges if relation_type(e.type).checked}
    lines = _header("Relationship view", "up")
    lines += [_node(graph, n, root=root) for n in sorted(ids)] + [""]
    lines += _edges(graph, ids, types)
    return "\n".join(lines) + "\n"


def dependency_view(graph: Graph) -> str:
    deps = graph.dependency_edges()
    ids = {e.source for e in deps} | {e.target for e in deps}
    lines = _header("Dependency view (requires, derives_from)", "up")
    lines += [_node(graph, n) for n in sorted(ids)] + [""]
    lines += _edges(graph, ids, {e.type for e in deps})
    return "\n".join(lines) + "\n"


def family_view(graph: Graph, families: list[str] | None = None) -> str:
    """One container per family; a document in several families appears in each."""
    names = list(graph.families) if families is None else families
    lines = _header("Family view", "right")
    for family in names:
        lines.append(f"{q('family:' + family)}: {{")
        lines.append(f"  label: {q(family)}")
        lines += [_node(graph, m, "  ") for m in graph.families.get(family, ())]
        lines += ["}", ""]
    loose = sorted(n for n, node in graph.nodes.items() if not node.families)
    if families is None and loose:
        lines += [f"{q('family:')}: {{", f"  label: {q('(no family)')}"]
        lines += [_node(graph, m, "  ") for m in loose]
        lines += ["}", ""]
    return "\n".join(lines).rstrip() + "\n"


def local_view(graph: Graph, root: str, depth: int) -> str:
    return relation_view(graph, graph.local(root, depth), root=root)
