#!/usr/bin/env python3
"""Independent ES acceptance comparisons and exhaustive small-domain checks.

Reads the deterministic brute/validate/fast results already generated by the
other two checkers. This program never invokes the larger-k search. Output is
exclusive-create; --check repeats every comparison and requires identical bytes.
The direct reference canonicalizer, extension DFS and edge-deletion DFS do not
import the specialized implementation. Every labelled q graph at k<=5 is
expanded explicitly before comparing the one-monochrome computation.
"""
from __future__ import annotations

import argparse
from collections import Counter
from hashlib import sha256
from itertools import product
import json
from pathlib import Path
import sys
from time import perf_counter

import c5_excess_two_finite_search as fast
import c5_excess_two_finite_search_brute as brute

ROOT = Path(__file__).resolve().parents[1]
DIRECTORY = ROOT / 'artifacts/c5_excess_two_finite_search'
NA_EXPECTED = {
    4: (2, 80, 40, 0, 0),
    5: (116, 4020, 3840, 240, 0),
    6: (5697, 182580, 175860, 4320, 1440),
}
CLASSES = ('edgesets', 'disk', 't4', 'q', 'crit')
D5 = tuple(tuple((direction * i + shift) % 5 for i in range(5))
           for direction in (-1, 1) for shift in range(5))
INPUT_KEYS = frozenset((kind, k, mode)
                      for kind, minimum in (('NA', 2), ('AD', 2), ('D6', 1))
                      for k in range(minimum, 7)
                      for mode in ('brute', 'validate', 'fast'))
E1_SOURCE_SHA = '23a92b56f325bd4bd496d7e8dfb14714d8481618253f88243df4cb7916ca999e'
E1_SOURCE_PATH = 'artifacts/c5_excess_rejection_law/observations.json'


def encode(value):
    return (json.dumps(value, sort_keys=True, indent=2) + '\n').encode()


def normalized_edges(values):
    return tuple(sorted(tuple(sorted(edge)) for edge in values))


def orbit(edges, kind, k):
    edges = normalized_edges(edges)
    return {
        tuple(sorted(tuple(sorted((mapping[a], mapping[b]))) for a, b in edges))
        for frame_map, private_map in product(D5, brute._private_permutations(kind, k))
        for mapping in (frame_map + private_map[5:],)
    }


def direct_deletions(edges, k):
    return {tuple(record['edge']): record['sigma_mask']
            for record in brute.deletion_sigmas(edges, k)}


def stored_deletions(record):
    values = record['deletion_sigmas']
    if isinstance(values, list):
        return {tuple(sorted(value['edge'])): value['sigma_mask'] for value in values}
    raise AssertionError('deletion_sigmas must be a list of named edge records')


def rejection(mask):
    return [p for p, row in enumerate(brute.REJECTION_INDEX) if not mask >> row & 1]


def q_components(q):
    points = set(q)
    if len(points) == 5:
        return 1
    return len(points) - sum(i in points and (i + 1) % 5 in points for i in range(5))


def shape(q):
    return min(tuple(sorted(mapping[i] for i in q)) for mapping in D5)


def validate_orbit_records(result):
    """Check exact masks, named deletion tables and actual full-group sizes."""
    kind, k = result['kind'], result['k']
    signatures = {}
    for category in ('q', 'crit'):
        by_canonical = {}
        for record in result[category + '_orbits']:
            edges = normalized_edges(record['canonical_edges'])
            images = orbit(edges, kind, k)
            canonical = min(images)
            assert record['orbit_size'] == len(images), (kind, k, category, 'orbit_size')
            assert brute.group_size(kind, k) % record['orbit_size'] == 0
            mask = brute.sigma_mask(edges, k)
            assert mask == record['sigma_mask'], (kind, k, category, 'stored sigma')
            assert record['Q'] == rejection(mask)
            assert mask & brute.T4 == brute.T4 and record['Q']
            deleted = direct_deletions(edges, k)
            assert deleted == stored_deletions(record), (kind, k, category, 'deletions')
            critical = all(value != mask for value in deleted.values())
            if category == 'crit':
                assert critical, (kind, k, 'noncritical graph in crit')
            assert canonical not in by_canonical, (kind, k, category, 'duplicate orbit')
            by_canonical[canonical] = len(images)
        assert sum(by_canonical.values()) == result['counts'][category]
        signatures[category] = by_canonical
    assert set(signatures['crit']) <= set(signatures['q'])
    return signatures


def onepass_named(edges, kind, k, sigma):
    adjacency = [0] * k
    spokes = [0] * k
    for a, b in edges:
        if a >= 5:
            adjacency[a - 5] |= 1 << (b - 5)
            adjacency[b - 5] |= 1 << (a - 5)
        elif b >= 5:
            spokes[b - 5] |= 1 << a
    hd = fast.HData(k, adjacency, kind)
    assert fast.sigma_of(hd, spokes) == sigma
    values = fast.crit_onepass(hd, spokes, sigma)
    named = {}
    for key, value in values.items():
        tag, (a, b) = key
        edge = (5 + a, 5 + b) if tag == 'h' else (b, 5 + a)
        named[tuple(sorted(edge))] = value
    return named


def check_every_labelled_q(result):
    kind, k = result['kind'], result['k']
    assert k <= 5
    seen = set()
    edges_checked = 0
    for record in result['q_orbits']:
        images = orbit(record['canonical_edges'], kind, k)
        assert len(images) == record['orbit_size']
        assert not seen & images
        for edges in sorted(images):
            mask = brute.sigma_mask(edges, k)
            expected = direct_deletions(edges, k)
            actual = onepass_named(edges, kind, k, mask)
            assert actual == expected, (kind, k, edges, 'one-monochrome mismatch')
            edges_checked += len(expected)
        seen.update(images)
    assert len(seen) == result['counts']['q']
    return dict(kind=kind, k=k, labelled_q_graphs=len(seen),
                nonframe_edge_deletions=edges_checked, mismatches=0)


def find_inputs(directory):
    results = {}
    inputs = []
    for path in sorted(directory.glob('*.json')):
        raw = path.read_bytes()
        value = json.loads(raw)
        schema = value.get('schema', '')
        if schema == 'c5-excess-two-brute-v1':
            mode = 'brute'
        elif value.get('mode') in ('validate', 'fast') and 'counts' in value and 'crit_orbits' in value:
            mode = value['mode']
        else:
            continue
        kind = value.get('kind', value.get('type'))
        k = value['k']
        key = (kind, k, mode)
        if key not in INPUT_KEYS:
            continue
        value['kind'] = kind
        assert key not in results, ('duplicate acceptance input', key)
        results[key] = value
        inputs.append(dict(path=path.relative_to(ROOT).as_posix(), sha256=sha256(raw).hexdigest()))
    assert set(results) == INPUT_KEYS, ('missing acceptance inputs', sorted(INPUT_KEYS - set(results)))
    return results, inputs


def relabel_control(record, kind):
    edges = normalized_edges(record['all_edges'])
    degrees = Counter(v for edge in edges for v in edge)
    private = sorted(v for v in record['vertices'] if v >= 5)
    roots = sorted(v for v in private if degrees[v] > 4)
    ordinary = sorted(set(private) - set(roots))
    assert len(roots) == (1 if kind == 'D6' else 2)
    ordered = roots + ordinary
    mapping = {v: v for v in range(5)} | {v: 5 + i for i, v in enumerate(ordered)}
    return normalized_edges((mapping[a], mapping[b]) for a, b in edges), len(private)


def positive_controls(results):
    archive_path = ROOT / 'artifacts/c5_excess_two_finite_search/positive_controls.json'
    raw = archive_path.read_bytes()
    archive = json.loads(raw)
    assert archive['schema'] == 'c5-es-positive-controls-v1'
    assert archive['source_path'] == E1_SOURCE_PATH
    assert archive['source_sha256'] == E1_SOURCE_SHA
    assert archive['source_size_bytes'] == 1125356
    assert [(record['kind'], record['k'], record['source_sigma_mask'])
            for record in archive['records']] == [('AD', 3, 935), ('D6', 5, 951)]
    # The exact two full records are archived in this task. Full E1 remains
    # optional: when present, verify both archived records against its bytes.
    # Optional availability is deliberately absent from deterministic output.
    source_path = ROOT / E1_SOURCE_PATH
    source = None
    if source_path.exists():
        original_bytes = source_path.read_bytes()
        assert sha256(original_bytes).hexdigest() == E1_SOURCE_SHA
        assert len(original_bytes) == archive['source_size_bytes']
        source = json.loads(original_bytes)
    output = []
    for archived in archive['records']:
        kind, k, mask = archived['kind'], archived['k'], archived['source_sigma_mask']
        original = archived['graph']
        assert sha256(encode(original)).hexdigest() == archived['record_sha256']
        assert archived['source_pointer'] == f'/exhaustive/{k-1}/minima_by_sigma/{mask}'
        if source is not None:
            assert original == source['exhaustive'][k - 1]['minima_by_sigma'][str(mask)]
        edges, size = relabel_control(original, kind)
        assert size == k
        assert brute.sigma_mask(edges, k) == mask
        assert all(value != mask for value in direct_deletions(edges, k).values())
        assert brute.planar_disk(edges, k, networkx_only=True)
        canonical = brute.canonical_form(edges, kind, k)
        expected = {brute.canonical_form(record['canonical_edges'], kind, k)
                    for record in results[kind, k, 'brute']['crit_orbits']}
        assert canonical in expected, (kind, k, 'missing E1 positive control')
        output.append(dict(kind=kind, k=k, original_sigma_mask=mask,
                           source_pointer=archived['source_pointer'],
                           original_record_sha256=archived['record_sha256'],
                           canonical_edges=[list(edge) for edge in canonical], found=True))
    return dict(path=E1_SOURCE_PATH, sha256=E1_SOURCE_SHA,
                archive_path=archive_path.relative_to(ROOT).as_posix(),
                archive_sha256=sha256(raw).hexdigest(), controls=output)


def run(directory=DIRECTORY):
    results, inputs = find_inputs(directory)
    comparisons = []
    checked = {}
    # Impossible small domains still receive an explicit degree-bound check.
    impossible = [('NA', 2), ('NA', 3), ('AD', 2)] + [('D6', k) for k in (1, 2, 3)]
    for kind, k in impossible:
        assert list(brute.internal_edge_sets(kind, k)) == []
        for mode in ('brute', 'validate', 'fast'):
            value = results[kind, k, mode]
            assert all(count == 0 or (name in ('disk', 't4') and mode == 'fast' and count is None)
                       for name, count in value['counts'].items())
            assert value['q_orbits'] == value['crit_orbits'] == []
    wanted = [('NA', k) for k in (4, 5, 6)] + [('AD', k) for k in (3, 4, 5)] + [('D6', k) for k in (4, 5)]
    wanted += [(kind, 6) for kind in ('AD', 'D6')]
    for kind, k in wanted:
        reference = results[kind, k, 'brute']
        specialized = results[kind, k, 'validate']
        assert reference['rows'] == [list(row) for row in brute.ROWS]
        assert specialized['patterns'] == reference['rows']
        assert specialized['counts'] == reference['counts'], (kind, k, 'class counts')
        if kind == 'NA':
            assert tuple(reference['counts'][name] for name in CLASSES) == NA_EXPECTED[k]
        checked[kind, k, 'brute'] = validate_orbit_records(reference)
        checked[kind, k, 'validate'] = validate_orbit_records(specialized)
        assert checked[kind, k, 'brute'] == checked[kind, k, 'validate'], (kind, k, 'canonical sets')
        comparisons.append(dict(kind=kind, k=k, counts=reference['counts'], counts_equal=True,
                                q_orbits=len(reference['q_orbits']), crit_orbits=len(reference['crit_orbits']),
                                canonical_q_sets_equal=True, canonical_crit_sets_equal=True,
                                orbit_weights_equal=True))
    criticality = [check_every_labelled_q(results[kind, k, 'brute'])
                  for kind, k in wanted if k <= 5]
    mode_comparisons = []
    for kind, minimum in (('NA', 4), ('AD', 3), ('D6', 4)):
        for k in range(minimum, 7):
            validate = results[kind, k, 'validate']
            accelerated = results[kind, k, 'fast']
            for mode, value in (('validate', validate), ('fast', accelerated)):
                key = kind, k, mode
                if key not in checked:
                    checked[key] = validate_orbit_records(value)
            assert checked[kind, k, 'validate'] == checked[kind, k, 'fast']
            assert validate['counts']['q'] == accelerated['counts']['q']
            assert validate['counts']['crit'] == accelerated['counts']['crit']
            q_diagnostics = ('q_shape_labelled', 'q_noncritical_edge_types',
                             'q_graphs_with_noncritical_type',
                             'q_noncritical_edge_count_histogram', 'q_noncritical_typesets')
            assert all(validate[name] == accelerated[name] for name in q_diagnostics)
            mode_comparisons.append(dict(kind=kind, k=k, labelled_q_count=validate['counts']['q'],
                                         labelled_crit_count=validate['counts']['crit'],
                                         crit_orbits=len(validate['crit_orbits']), canonical_crit_sets_equal=True,
                                         q_orbits=len(validate['q_orbits']), canonical_q_sets_equal=True,
                                         q_diagnostics_equal=True, orbit_weights_equal=True,
                                         fast_support_lemma_pruned_nodes=accelerated['diagnostics'].get(
                                             'support_lemma_pruned_nodes', 0)))
    na6 = results['NA', 6, 'validate']['crit_orbits']
    assert len(na6) == 3 and sorted(record['orbit_size'] for record in na6) == [480, 480, 480]
    guide_controls = {
        'NA6-1': '01,04,05,06,07,08,12,15,25,23,34,39,3a,47,49,58,5a,67,68,69,6a,79,8a',
        'NA6-3': '01,04,05,06,07,08,12,15,25,29,23,34,36,39,46,57,59,68,6a,78,7a,8a,9a',
    }
    na6_canon = {brute.canonical_form(record['canonical_edges'], 'NA', 6) for record in na6}
    identities = []
    for name, compact in guide_controls.items():
        edges = normalized_edges((int(pair[0], 16), int(pair[1], 16)) for pair in compact.split(','))
        canonical = brute.canonical_form(edges, 'NA', 6)
        assert canonical in na6_canon, ('missing guide positive control', name)
        identities.append(dict(name=name, canonical_edges=[list(edge) for edge in canonical], found=True))
    # NA6-2 changes the NA6-1 root-w spoke 06 to 36 and retains all other original named edges.
    edges1 = normalized_edges((int(pair[0], 16), int(pair[1], 16)) for pair in guide_controls['NA6-1'].split(','))
    edges2 = tuple(sorted((set(edges1) - {(0, 6)}) | {(3, 6)}))
    canonical2 = brute.canonical_form(edges2, 'NA', 6)
    assert canonical2 in na6_canon and canonical2 != tuple(map(tuple, identities[0]['canonical_edges']))
    identities.append(dict(name='NA6-2', canonical_edges=[list(edge) for edge in canonical2], found=True))
    identities.sort(key=lambda record: record['name'])
    assert len({tuple(map(tuple, record['canonical_edges'])) for record in identities}) == 3
    controls = positive_controls(results)
    all32 = []
    triples = {frozenset(mapping[i] for i in (0, 1, 3)) for mapping in D5}
    for mask in range(32):
        q = [i for i in range(5) if mask >> i & 1]
        contains = any(triple <= set(q) for triple in triples)
        assert (len(q) + q_components(q) > 4) == contains
        all32.append(dict(Q=q, c_Q=q_components(q), Q_plus_c_Q=len(q) + q_components(q),
                          contains_941_triple=contains))
    return dict(schema='c5-excess-two-validation-v1', acceptance_passed=True,
                inputs=inputs, impossible_degree_domains=[dict(kind=kind, k=k, edgesets=0) for kind, k in impossible],
                brute_validate_comparisons=comparisons, onepass_all_labelled_q=criticality,
                fast_validate_comparisons=mode_comparisons, na6_positive_controls=identities,
                e1_positive_controls=controls, all_32_Q_subsets=all32)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--directory', type=Path, default=DIRECTORY)
    parser.add_argument('--output', type=Path, default=DIRECTORY / 'validation.json')
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    started = perf_counter()
    result = run(args.directory)
    payload = encode(result)
    if args.check:
        assert args.output.read_bytes() == payload, 'validation artifact differs from exact byte replay'
        status = 'CHECK OK'
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        with args.output.open('xb') as stream:
            stream.write(payload)
        status = 'GENERATED'
    print(f'{status}: all ES acceptance comparisons; '
          f'{sum(record["labelled_q_graphs"] for record in result["onepass_all_labelled_q"])} labelled q graphs, '
          f'{sum(record["nonframe_edge_deletions"] for record in result["onepass_all_labelled_q"])} edge deletions; '
          f'{perf_counter() - started:.3f} seconds; {args.output}', flush=True)
    return 0


if __name__ == '__main__':
    sys.exit(main())
