#!/usr/bin/env python3
"""Large artifacts: kept on disk, not in git, reproduced from their scripts.

artifacts/MANIFEST.json (tracked) records, for every generated file of at least
1 MB (except FROZEN ones), its sha256, size and producing script, plus the
dependency order between producers.  The files themselves are listed in a
generated block of .gitignore.  Dependencies come from the paths named in each
script and from missing-input failures seen during a rebuild, which are saved.
Each producer's fingerprint (its code, the scripts/*.py it imports or names, and
the recorded hashes of its inputs) is saved when its output is verified; a
changed fingerprint marks it and everything downstream stale.

python tools/artifacts.py status              # ok / missing / changed / stale (producer code or inputs changed)
python tools/artifacts.py rebuild [-j N]      # rerun producers of missing, changed or stale files, N at a time
python tools/artifacts.py rebuild --all       # rerun every producer, verify byte-identical output
python tools/artifacts.py record [PATH ...]   # accept current bytes (after an intended change);
                                              # with no PATH: rescan artifacts/ for large files

Run under the pinned environment:  uv run --with-requirements requirements.txt python tools/artifacts.py ...
A rebuild moves each existing output aside first; a mismatching rerun is kept as
<path>.rebuilt and the recorded file is restored (--keep-going instead leaves the
new bytes in place so downstream producers still run).  Exit status 1 on any failure.
"""
from __future__ import annotations

import argparse
from concurrent.futures import FIRST_COMPLETED, ThreadPoolExecutor, wait
from graphlib import TopologicalSorter
from hashlib import sha256
from importlib import metadata
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import time

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / 'artifacts/MANIFEST.json'
GITIGNORE = ROOT / '.gitignore'
REQUIREMENTS = ROOT / 'requirements.txt'
THRESHOLD = 1_000_000
SCRATCH = {'.pre-rebuild', '.rebuilt', '.recorded'}
BEGIN = '# BEGIN generated by tools/artifacts.py: large artifacts, reproduced via artifacts/MANIFEST.json'
END = '# END generated by tools/artifacts.py'
# Large file that stays in git because its producer can no longer reproduce it byte for byte.
FROZEN = {
    # legacy certificate: docs/c5_single_spoke_cores.md changed after it was written;
    # c5_adjacent_degree5_no_mixed_t2_t0_pairs.py replays it and requires the saved bytes
    'artifacts/c5_single_spoke_two_two/observations.json',
}
# Outputs whose producer cannot be read off an `OUT = ROOT / '...'` style assignment.
PRODUCER_OVERRIDES = {
    'artifacts/automata/': 'triangle_automata.py',
    'artifacts/stepwise/layer_refinement.json': 'stepwise_layer_refinement.py',
    'artifacts/c5_no_mixed_hypothesis_audit/anchor.json': 'c5_no_mixed_hypothesis_anchor.py',
}


def file_sha(path):
    h = sha256()
    with open(path, 'rb') as f:
        for block in iter(lambda: f.read(1 << 20), b''):
            h.update(block)
    return h.hexdigest()


def load():
    return json.loads(MANIFEST.read_text()) if MANIFEST.exists() else dict(files={}, producers={})


def save(manifest):
    MANIFEST.write_text(json.dumps(manifest, ensure_ascii=False, sort_keys=True, indent=1) + '\n')


def script_text(name):
    return (ROOT / 'scripts' / name).read_text()


def infer_producer(path):
    for prefix, script in PRODUCER_OVERRIDES.items():
        if path.startswith(prefix):
            return script
    directory = path.split('/')[1]
    exact, by_directory = [], []
    for script in sorted((ROOT / 'scripts').glob('*.py')):
        if script.name.startswith('check_'):
            continue
        text = script.read_text()
        for target, found in ((path, exact), ('artifacts/' + directory, by_directory)):
            literal = r'''["']%s["']''' % re.escape(target)
            if (re.search(r'^[A-Z_0-9]*OUT[A-Z_0-9]*\s*=.*/\s*' + literal, text, re.M)
                    or re.search(r'default\s*=\s*(?:str\()?ROOT\s*/\s*' + literal, text)):
                found.append(script.name)
    found = exact or by_directory
    if len(found) > 1 and directory + '.py' in found:
        found = [directory + '.py']
    if len(found) != 1:
        sys.exit(f'{path}: cannot infer producer (candidates {found}); add it to PRODUCER_OVERRIDES')
    return found[0]


def infer_needs(manifest):
    """Producer P needs producer Q when P's source names a file Q produces, or when a
    rebuild learned it from a missing-input failure (kept from the manifest)."""
    scripts = {entry['script'] for entry in manifest['files'].values()}
    needs = {}
    for script in sorted(scripts):
        text = script_text(script)
        learned = set(manifest['producers'].get(script, [])) & scripts
        needs[script] = sorted(learned | {entry['script'] for path, entry in manifest['files'].items()
                                          if entry['script'] != script and _mentions(text, path)})
    return needs


def _mentions(text, path):
    if path in text or path.removeprefix('artifacts/') in text:
        return True
    directory, name = path.rsplit('/', 1)
    return f"'{directory}'" in text and f"'{name}'" in text or f'"{directory}"' in text and f'"{name}"' in text


def order(manifest):
    return list(TopologicalSorter({p: set(n) for p, n in manifest['producers'].items()}).static_order())


def state(path, entry):
    full = ROOT / path
    if not full.exists():
        return 'missing'
    if full.stat().st_size != entry['bytes'] or file_sha(full) != entry['sha256']:
        return 'changed'
    return 'ok'


def code_closure(script):
    """The producer plus every scripts/*.py it imports or names in a string, transitively."""
    seen, todo = set(), [script]
    while todo:
        name = todo.pop()
        if name in seen:
            continue
        seen.add(name)
        text = script_text(name)
        refs = re.findall(r'^\s*(?:from|import)\s+(\w+)', text, re.M)
        refs += re.findall(r'''["'](?:scripts/)?(\w+)\.py["']''', text)
        todo.extend(f'{ref}.py' for ref in refs if (ROOT / 'scripts' / f'{ref}.py').exists())
    return sorted(seen)


def fingerprint(script, manifest):
    """What a producer's recorded output was built from: its code closure and the
    recorded hashes of the files its needs produce."""
    h = sha256()
    for name in code_closure(script):
        h.update(f'scripts/{name}\0'.encode() + (ROOT / 'scripts' / name).read_bytes() + b'\0')
    needs = set(manifest['producers'].get(script, []))
    for path, entry in sorted(manifest['files'].items()):
        if entry['script'] in needs:
            h.update(f'{path}\0{entry["sha256"]}\0'.encode())
    return h.hexdigest()


def stale_producers(manifest):
    """Producers whose fingerprint changed since their output was verified, and everything
    downstream of them (an upstream rerun may change what they read)."""
    recorded = manifest.get('fingerprints', {})
    stale = set()
    for script in order(manifest):
        if (recorded.get(script) != fingerprint(script, manifest)
                or any(n in stale for n in manifest['producers'][script])):
            stale.add(script)
    return stale


def check_environment():
    want = f"{sys.version_info.major}.{sys.version_info.minor}"
    notes = []
    python = load().get('python')
    if python and python != want:
        notes.append(f'python {want} (recorded with {python})')
    for line in REQUIREMENTS.read_text().split('\n'):
        line = line.split('#')[0].strip()
        if '==' not in line:
            continue
        name, version = line.split('==')
        try:
            have = metadata.version(name)
        except metadata.PackageNotFoundError:
            have = None
        if have != version:
            notes.append(f'{name} {have or "not installed"} (requirements.txt pins {version})')
    for note in notes:
        print(f'warning: {note}', file=sys.stderr)


def cmd_status(args):
    manifest = load()
    stale = stale_producers(manifest)
    counts = {}
    for path, entry in sorted(manifest['files'].items()):
        s = state(path, entry)
        if s == 'ok' and entry['script'] in stale:
            s = 'stale'
        counts[s] = counts.get(s, 0) + 1
        if s != 'ok' or args.verbose:
            print(f'{s:8s} {path}  <- scripts/{entry["script"]}')
    print(' '.join(f'{k}={v}' for k, v in sorted(counts.items())))
    return 0 if set(counts) <= {'ok'} else 1


def run_producer(script, paths, manifest, keep_going):
    """Run one producer with its recorded outputs moved aside; return (run, seconds, mismatching paths)."""
    aside = {}
    for path in paths:
        full = ROOT / path
        if full.exists():
            aside[path] = full.with_name(full.name + '.pre-rebuild')
            full.rename(aside[path])
    started = time.monotonic()
    run = subprocess.run([sys.executable, str(ROOT / 'scripts' / script)], cwd=ROOT,
                         stdout=subprocess.DEVNULL, stderr=subprocess.PIPE, text=True)
    seconds = time.monotonic() - started
    bad = []
    for path in sorted(paths):
        full = ROOT / path
        if run.returncode == 0 and state(path, manifest['files'][path]) == 'ok':
            if path in aside:
                aside[path].unlink()
            continue
        bad.append(path)
        if run.returncode == 0 and keep_going:
            if path in aside:
                aside[path].rename(full.with_name(full.name + '.recorded'))
            continue
        if full.exists():
            full.rename(full.with_name(full.name + '.rebuilt'))
        if path in aside:
            aside[path].rename(full)
    return run, seconds, bad


def missing_input(stderr, manifest):
    for match in re.finditer(r"No such file or directory: '([^']+)'", stderr):
        path = Path(match.group(1))
        path = str((path if path.is_absolute() else ROOT / path).resolve().relative_to(ROOT))
        if path in manifest['files']:
            return path
    return None


def cmd_rebuild(args):
    """Run the selected producers, at most --jobs at a time, each once all its needs are done.

    Producer states: pending -> running -> ok | mismatch | failed; pending -> blocked when a
    need ended badly.  A missing-input failure adds the edge, saves it and returns to pending.
    """
    check_environment()
    manifest = load()
    outputs = {}
    for path, entry in manifest['files'].items():
        outputs.setdefault(entry['script'], []).append(path)
    if args.all:
        selected = set(outputs)
    else:
        selected = stale_producers(manifest) | {manifest['files'][p]['script'] for p in manifest['files']
                                                if state(p, manifest['files'][p]) != 'ok'}
    status = {script: 'pending' for script in selected}
    passable = {'ok', 'mismatch'} if args.keep_going else {'ok'}
    rank = {script: i for i, script in enumerate(order(manifest))}
    running = {}

    def report(tag, text):
        finished = sum(s not in ('pending', 'running') for s in status.values())
        print(f'[{finished:3d}/{len(status)} run {len(running)}] {tag:8s} {text}')

    with ThreadPoolExecutor(max_workers=args.jobs) as pool:
        while True:
            for script in sorted((s for s, v in status.items() if v == 'pending'), key=rank.get):
                needs = [n for n in manifest['producers'][script] if n in status]
                if bad := [n for n in needs if status[n] in ('failed', 'blocked')
                                                   or status[n] == 'mismatch' and not args.keep_going]:
                    status[script] = 'blocked'
                    report('BLOCKED', f'scripts/{script}  (needs {", ".join(bad)})')
                elif len(running) < args.jobs and all(status[n] in passable for n in needs):
                    status[script] = 'running'
                    running[pool.submit(run_producer, script, outputs[script], manifest,
                                        args.keep_going)] = script
            if not running:
                break
            finished, _ = wait(running, return_when=FIRST_COMPLETED)
            for future in finished:
                script = running.pop(future)
                run, seconds, bad = future.result()
                missing = missing_input(run.stderr, manifest) if run.returncode else None
                upstream = missing and manifest['files'][missing]['script']
                needs = manifest['producers'][script]
                if upstream and upstream != script and upstream not in needs:
                    # a dependency the static scan missed: record it and retry after the upstream producer
                    manifest['producers'][script] = sorted(needs + [upstream])
                    save(manifest)
                    rank = {s: i for i, s in enumerate(order(manifest))}
                    status.setdefault(upstream, 'pending')
                    status[script] = 'pending'
                    report('learned', f'scripts/{script} needs scripts/{upstream}')
                    continue
                if run.returncode != 0:
                    status[script] = 'failed'
                    report('FAIL', f'scripts/{script} exit {run.returncode} ({seconds:.0f}s)\n'
                           + run.stderr.strip()[-2000:])
                elif bad:
                    status[script] = 'mismatch'
                    for path in bad:
                        report('MISMATCH', f'{path}  <- scripts/{script}')
                else:
                    status[script] = 'ok'
                    manifest.setdefault('fingerprints', {})[script] = fingerprint(script, manifest)
                    save(manifest)
                    report('ok', f'scripts/{script} ({seconds:.0f}s, {len(outputs[script])} file(s))')
    stuck = [s for s, v in status.items() if v == 'pending']
    for script in stuck:
        print(f'STUCK    scripts/{script}  (dependency cycle?)')
    counts = {}
    for value in status.values():
        counts[value] = counts.get(value, 0) + 1
    print(' '.join(f'{k}={v}' for k, v in sorted(counts.items())))
    return 0 if set(counts) <= {'ok'} else 1


def cmd_record(args):
    manifest = load()
    if args.paths:
        paths = [str(Path(p).resolve().relative_to(ROOT)) for p in args.paths]
    else:
        paths = sorted(set(manifest['files']) | {
            str(p.relative_to(ROOT)) for p in (ROOT / 'artifacts').rglob('*')
            if p.is_file() and p.stat().st_size >= THRESHOLD and p.suffix not in SCRATCH} - FROZEN)
    for path in paths:
        if path in FROZEN:
            sys.exit(f'{path}: frozen, stays tracked in git (see FROZEN)')
        full = ROOT / path
        if not full.exists():
            sys.exit(f'{path}: missing; rebuild it before recording')
        entry = manifest['files'].get(path) or dict(script=infer_producer(path))
        entry.update(sha256=file_sha(full), bytes=full.stat().st_size)
        manifest['files'][path] = entry
    manifest['python'] = f"{sys.version_info.major}.{sys.version_info.minor}"
    manifest['producers'] = infer_needs(manifest)
    order(manifest)  # reject cycles
    fingerprints = manifest.setdefault('fingerprints', {})
    for script in list(fingerprints):
        if script not in manifest['producers']:
            del fingerprints[script]
    for script in sorted({manifest['files'][p]['script'] for p in paths}):
        fingerprints[script] = fingerprint(script, manifest)
    save(manifest)
    write_gitignore(manifest)
    print(f'recorded {len(paths)} file(s); manifest holds {len(manifest["files"])} from '
          f'{len(manifest["producers"])} producer(s)')
    return 0


def write_gitignore(manifest):
    text = GITIGNORE.read_text() if GITIGNORE.exists() else ''
    block = '\n'.join([BEGIN, *('/' + p for p in sorted(manifest['files'])), END])
    if BEGIN in text:
        head, rest = text.split(BEGIN, 1)
        text = head + block + rest.split(END, 1)[1]
    else:
        text = text.rstrip('\n') + '\n\n' + block + '\n'
    GITIGNORE.write_text(text)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest='command', required=True)
    status = sub.add_parser('status')
    status.add_argument('-v', '--verbose', action='store_true')
    status.set_defaults(func=cmd_status)
    rebuild = sub.add_parser('rebuild')
    rebuild.add_argument('--all', action='store_true')
    rebuild.add_argument('-j', '--jobs', type=int, default=max(1, (os.cpu_count() or 1) // 4),
                         help='producers run at the same time (default: a quarter of the CPUs)')
    rebuild.add_argument('--keep-going', action='store_true',
                         help='leave mismatching output in place (recorded bytes kept as <path>.recorded) '
                              'so downstream producers still run')
    rebuild.set_defaults(func=cmd_rebuild)
    record = sub.add_parser('record')
    record.add_argument('paths', nargs='*')
    record.set_defaults(func=cmd_record)
    args = parser.parse_args()
    sys.stdout.reconfigure(line_buffering=True)
    sys.exit(args.func(args))


if __name__ == '__main__':
    main()
